---
title: "Log Abundance by Year"
author: "Tiffany Winter"
date: "11/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
library(tinytex)

hampton <- read.csv("R_HHHR2.csv" , stringsAsFactors = TRUE)
cml <- read.csv("R_UNH_Pier.csv", stringsAsFactors = TRUE)

colnames(hampton)<- c("Week", "Date", "Month", "Day", "Year", "Station", "Alex", "Large_PN", "Small_PN")

colnames(cml)<- c("Week", "Date", "Month", "Day", "Year", "Station", "Alex", "Large_PN", "Small_PN", 
                       "Chlorophyl", "PAR", "Temp", "Salinity")


cml$Alex <- as.numeric(cml$Alex)
cml$Large_PN <- as.numeric(cml$Large_PN)
cml$Small_PN <- as.numeric(cml$Small_PN)

hampton$Alex <- as.numeric(hampton$Alex)
hampton$Large_PN <- as.numeric(hampton$Large_PN)
hampton$Small_PN <- as.numeric(hampton$Small_PN)


```


```{r, fig.cap= "The log of *Alexandrium* abundance (cells/l) by year at the HHHR2 (Hampton, NH) sampling site"}
ggplot(hampton[which(hampton$Alex>0),], 
       mapping = aes(x = Year, y = Alex)) + 
  geom_point() +
  scale_y_log10(labels = function(x) format(x, scientific = TRUE)) +
  theme_classic() + 
  labs(x = "Year", y = "Abundance (Cells/l)")
```


```{r, fig.cap= "The log of large sized ($\\geq$ 3$\\mu$m) *Pseudo-nitzschia* abundance (cells/l) by year at the HHHR2 (Hampton, NH) sampling site"}
ggplot(hampton[which(hampton$Large_PN>0),], 
       mapping = aes(x = Year, y = Large_PN)) + 
  geom_point() +
  scale_y_log10(labels = function(x) format(x, scientific = TRUE)) +
  theme_classic() + 
  labs(x = "Year", y = "Abundance (Cells/l)")
```


```{r, fig.cap= "The log of small sized (< 3$\\mu$m) *Pseudo-nitzschia* abundance (cells/l) by year at the HHHR2 (Hampton, NH) sampling site"}
ggplot(hampton[which(hampton$Small_PN>0),], 
       mapping = aes(x = Year, y = Small_PN)) + 
  geom_point() +
  scale_y_log10(labels = function(x) format(x, scientific = TRUE)) +
  theme_classic() + 
  labs(x = "Year", y = "Abundance (Cells/l)")
```


```{r, fig.cap= "The log of *Alexandrium* abundance (cells/l) by year at the UNH Pier (CML, Newington, NH) sampling site"}
ggplot(cml[which(cml$Alex>0),], 
       mapping = aes(x = Year, y = Alex)) + 
  geom_point() +
  scale_y_log10(labels = function(x) format(x, scientific = TRUE)) +
  theme_classic() + 
  labs(x = "Year", y = "Abundance (Cells/l)")
```


```{r, fig.cap= "The log of large sized ($\\geq$ 3$\\mu$m) *Pseudo-nitzschia* abundance (cells/l) by year at the UNH Pier (CML, Newington, NH) sampling site"}
ggplot(cml[which(cml$Large_PN>0),], 
       mapping = aes(x = Year, y = Large_PN)) + 
  geom_point() +
  scale_y_log10(labels = function(x) format(x, scientific = TRUE)) +
  theme_classic() + 
  labs(x = "Year", y = "Abundance (Cells/l)")
```


```{r, fig.cap= "The log of small sized (< 3$\\mu$m) *Pseudo-nitzschia* abundance (cells/l) by year at the UNH Pier (CML, Newington, NH) sampling site"}
ggplot(cml[which(cml$Small_PN>0),], 
       mapping = aes(x = Year, y = Small_PN)) + 
  geom_point() +
  scale_y_log10(labels = function(x) format(x, scientific = TRUE)) +
  theme_classic() + 
  labs(x = "Year", y = "Abundance (Cells/l)")
```
