---
title: "Month Sums"
author: "Tiffany Winter"
date: "2/3/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(ggplot2)
library(tinytex)
library(dplyr)
library(tidyr)


hampton <- read.csv("R_HHHR2.csv" , stringsAsFactors = TRUE)
cml <- read.csv("R_UNH_Pier.csv", stringsAsFactors = TRUE)

colnames(hampton)<- c("Week", "Date", "Month", "Day", "Year", "Station", "Alex", "Large_PN", "Small_PN")

colnames(cml)<- c("Week", "Date", "Month", "Day", "Year", "Station", "Alex", "Large_PN", "Small_PN", 
                  "Chlorophyl", "PAR", "Temp", "Salinity")

cols <- c("2017"="red", "2018"="blue", "2019"="purple", "2020"="green", "2021"="black")

cml_month <- cml %>% 
  group_by(Year, Month) %>% 
  summarize_at(c("Alex", "Large_PN", "Small_PN"), sum, na.rm = TRUE)

hampton_month <- hampton %>% 
  group_by(Year, Month) %>% 
  summarize_at(c("Alex", "Large_PN", "Small_PN"), sum, na.rm = TRUE)
```


```{r, fig.cap="The log of the monthly sum of *Alexandrium* (cells/l) at the UNH Pier (New Castle, NH) sampling site. The months run from January (J) to December (D)."}
ggplot(cml_month, mapping = aes(x = Month, y = Alex, color = Year)) + 
  geom_point(aes(color = factor(Year))) +
  scale_color_manual(values = cols) +
  scale_y_log10() +
  scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12),
                     labels = c("J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D")) +
  theme_classic() + 
  labs(x = "Month", y = "Log Total Abundance (Cells/l)")
```


```{r, fig.cap="The log of the monthly sum of large ($\\geq$ 3$\\mu$m) *Pseudo-nitzschia* (cells/l) at the UNH Pier (New Castle, NH) sampling site. The months run from January (J) to December (D)."}
ggplot(cml_month, mapping = aes(x = Month, y = Large_PN, color = Year)) + 
  geom_point(aes(color = factor(Year))) +
  scale_color_manual(values = cols) +
  scale_y_log10() +
  scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12),
                     labels = c("J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D")) +
  theme_classic() + 
  labs(x = "Month", y = "Log Total Abundance (Cells/l)")
```

```{r, fig.cap="The log of the monthly sum of small (< 3$\\mu$m) *Pseudo-nitzschia* (cells/l) at the UNH Pier (New Castle, NH) sampling site. The months run from January (J) to December (D)."}
ggplot(cml_month, mapping = aes(x = Month, y = Small_PN, color = Year)) + 
  geom_point(aes(color = factor(Year))) +
  scale_color_manual(values = cols) +
  scale_y_log10() +
  scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12),
                     labels = c("J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D")) +
  theme_classic() + 
  labs(x = "Month", y = "Log Total Abundance (Cells/l)")
```


```{r, fig.cap="The log of the monthly sum of *Alexandrium* (cells/l) at the HHHR2 (Hampton, NH) sampling site. The months run from January (J) to December (D)."}
ggplot(hampton_month, mapping = aes(x = Month, y = Alex, color = Year)) + 
  geom_point(aes(color = factor(Year))) +
  scale_color_manual(values = cols) +
  scale_y_log10() +
  scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12),
                     labels = c("J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D")) +
  theme_classic() + 
  labs(x = "Month", y = "Log Total Abundance (Cells/l)")
```

```{r, fig.cap="The log of the monthly sum of large ($\\geq$ 3$\\mu$m) *Pseudo-nitzschia* (cells/l) at the HHHR2 (Hampton, NH) sampling site. The months run from January (J) to December (D)."}
ggplot(hampton_month, mapping = aes(x = Month, y = Large_PN, color = Year)) + 
  geom_point(aes(color = factor(Year))) +
  scale_color_manual(values = cols) +
  scale_y_log10() +
  scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12),
                     labels = c("J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D")) +
  theme_classic() + 
  labs(x = "Month", y = "Log Total Abundance (Cells/l)")
```


```{r, fig.cap="The log of the monthly sum of small (< 3$\\mu$m) *Pseudo-nitzschia* (cells/l) at the HHHR2 (Hampton, NH) sampling site. The months run from January (J) to December (D)."}
ggplot(hampton_month, mapping = aes(x = Month, y = Small_PN, color = Year)) + 
  geom_point(aes(color = factor(Year))) +
  scale_color_manual(values = cols) +
  scale_y_log10() +
  scale_x_continuous(breaks = c(1,2,3,4,5,6,7,8,9,10,11,12),
                     labels = c("J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D")) +
  theme_classic() + 
  labs(x = "Month", y = "Log Total Abundance (Cells/l)")
```

